language: node_js
node_js:
  - node

install:
  - npm install
script:
  - commitlint-travis
  - npm run test

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx travis-deploy-once "npx semantic-release"
